---
output: 
  html_document:
    theme: lumen
runtime: shiny
lang: "nl"
editor_options: 
  markdown:
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE)
```

```{r libraries, warning=FALSE}
library(ggplot2)
library(renz)
```

```{r dataprep}
# Helper functions
parse_input <- function(conc_input, act_input) {
  conc <- as.numeric(unlist(strsplit(conc_input, ",")))
  act <- as.numeric(unlist(strsplit(act_input, ",")))
  
  if (length(conc) != length(act)) {
    return(NULL)
  }
  data.frame(
    concentration = conc,
    activity = act
  )
}
```

```{r}
div(
  style = "background-color:#2C3E50; padding:25px; border-radius:10px; margin-bottom:20px; margin-top:20px;",
  h2("MM-curve fitting applicatie",
     style = "color:#F8F9FA; margin:0; font-weight:600;")
)
```

```{r tabpanels}
tabsetPanel(
  tabPanel("Welkom",
           p("In deze applicatie kun je een MM-curve fitten door gemeten datapunten. Er is keuze uit een
             enkele curve en een dubbele curve.")),
  tabPanel("Enkele curve",
           p("Gebaseerd op gemeten activiteiten (v) bij gegeven concentraties (S) wordt een MM-curve gefit
             door de datapunten."),
           p("! Gebruik een '.' als decimaalteken."),
           wellPanel(
               textInput("new_conc", "Voer concentratie in (gescheiden door komma):", placeholder = "Voorbeeld: 1.25, 0.90, 0.60, 0.31, 0.16, 0.08, 0.04, 0.02, 0.01", width = "100%"),
               textInput("new_act", "Voer activiteit in (gescheiden door komma):", placeholder = "Voorbeeld: 1.12e-01, 9.90e-02, 1.10e-01, 9.66e-02, 7.27e-02, 4.80e-02, 2.75e-02, 0.00e00, 6.71e-03", width = "100%"),
               actionButton("fit_single", "Maak plot")
           ),
           
           br(),
           plotOutput("single_plot", height = "400px")
           ),
  
  tabPanel("Dubbele curve",
           p("Gebaseerd op gemeten activiteiten (v) bij gegeven concentraties (S) wordt een MM-curve gefit
             voor twee sets aan gemeten datapunten."),
           p("! Gebruik een '.' als decimaalteken."),
           wellPanel(
             textInput("new_conc1", "Voer concentratie in voor dataset 1 (gescheiden door komma):", placeholder =
                         "Voorbeeld: 1.25, 0.90, 0.60, 0.31, 0.16, 0.08, 0.04, 0.02, 0.01", width = "100%"),
             textInput("new_act1", "Voer activiteit in voor dataset 1 (gescheiden door komma):", placeholder =
             "Voorbeeld: 1.12e-01, 9.90e-02, 1.10e-01, 9.66e-02, 7.27e-02, 4.80e-02, 2.75e-02, 0.00e00, 6.71e-03", width = "100%"),
             
             textInput("new_conc2", "Voer concentratie in voor dataset 2 (gescheiden door komma):", placeholder =
                         "Voorbeeld: 1.25, 0.90, 0.60, 0.31, 0.16, 0.08, 0.04, 0.02, 0.01", width = "100%"),
                         textInput("new_act2", "Voer activiteit in voor datatset 2 (gescheiden door komma):",
                         placeholder = "Voorbeeld: 1.12e-01, 9.90e-02, 1.10e-01, 9.66e-02, 7.27e-02, 4.80e-02, 2.75e-02, 0.00e00, 6.71e-03", width = "100%"),
             actionButton("fit_double", "Maak plot")
             ),
           
           br(),
           plotOutput("double_plot", height = "400px")
           ),
  
  tabPanel("Info en contact",
           h3("Hoe komt de fit tot stand?"),
           p("De Michaelis-Menten vergelijking wordt in deze applicatie gefit met behulp van non linear
           least-squares fitting. Deze methode bepaalt de waarden \\(V_{max}\\) en \\(K_m\\) waarbij het verschil
           tussen de gemeten reactiesnelheden en de door het model voorspelde waarden zo klein mogelijk wordt
           gemaakt. De berekening wordt uitgevoerd met de functie", code("dir.MM()"), "uit de R-package",
           a("Renz", href = "https://cran.r-project.org/web/packages/renz/index.html"), "."),
           p("De", a("Michaelis-Menten vergelijking", href =
                       "https://nl.wikipedia.org/wiki/Michaelis-Mentenvergelijking"), "beschrijft de
             enzymkinetiek aan de hand van onderstaand model:"),
           p("$$v = \\frac{V_{\\max}[S]}{K_m + [S]}$$"),
           p("Parameters:"),
           withMathJax(
           HTML("
           <ul>
           <li>\\(V_{\\max}\\): de maximale reactiesnelheid</li>
           <li>\\(K_m\\): een maat voor affiniteit van het enzym voor het substraat</li>
           <li>\\(S\\): de substraatconcentratie</li>
           </ul>
           ")
           ),
           
           h3("Contactgegevens"),
           p("Deze applicatie is ontwikkeld door Mirte Draaijer gedurende de minor DNA sequencing en biologische
           data-analyse bij NHL Stenden & Van Hall Larenstein.
           Voor contact verwijs ik graag naar de", 
           a("github", href = "https://github.com/MirteDraaijer/excelproject/tree/main", target = "_blank"),
           "van deze applicatie of naar mijn",
           a("LinkedIn pagina", href = "https://www.linkedin.com/in/mirte-draaijer-394a58385/"), target =
             "_blank", ".")
  )
)
```

```{r parse_single}
# Enkele curve:
single_data <- eventReactive(input$fit_single, {
  req(input$new_conc, input$new_act)
  data <- parse_input(input$new_conc, input$new_act)
  
  validate(
    need(length(data$concentration) > 0 && length(data$activity) > 0,
         "Voer waarden in gescheiden door komma's."),
    need(!any(is.na(data$concentration)) &&
           !any(is.na(data$activity)),
         "Gebruik alleen numeriek waarden (geen tekst)."),
    need(length(data$concentration) == length(data$activity),
         "Aantal concentraties en activiteiten moet gelijk zijn.")
  )
  data
})
```

```{r fit_single}
single_fit <- eventReactive(input$fit_single, {
  req(single_data())
  dir.MM(single_data(), plot = FALSE)
})
```

```{r single_plot}
output$single_plot <- renderPlot({
  req(single_data(), single_fit())
  
  ggplot(single_data(), aes(x = concentration, y = activity)) +
    geom_point(color = "brown2", shape = 18, size = 3) +
    geom_line(data = single_fit()$data,
              aes(x = S, y = fitted_v),
              color = "deepskyblue2",
              size = 1) +
    labs(
      title = "MM-curve gefit door gemeten datapunten",
      x = "Concentratie",
      y = "Activiteit"
    ) +
    theme_minimal() +
    theme(
      plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
      axis.title = element_text(face = "bold")
    )
})
```

```{r parse_double}
# Dubbele curve:
data1 <- eventReactive(input$fit_double, {
  req(input$new_conc1, input$new_act1)
  data <- parse_input(input$new_conc1, input$new_act1)
  
  validate(
    need(length(data$concentration) > 0 && length(data$activity) > 0,
         "Voer waarden in gescheiden door komma's."),
    need(!any(is.na(data$concentration)) &&
           !any(is.na(data$activity)),
         "Gebruik alleen numeriek waarden (geen tekst)."),
    need(length(data$concentration) == length(data$activity),
         "Aantal concentraties en activiteiten moet gelijk zijn.")
  )
  data
})

data2 <- eventReactive(input$fit_double, {
  req(input$new_conc2, input$new_act2)
  data <- parse_input(input$new_conc2, input$new_act2)
  
  validate(
    need(length(data$concentration) > 0 && length(data$activity) > 0,
         "Voer waarden in gescheiden door komma's."),
    need(!any(is.na(data$concentration)) &&
           !any(is.na(data$activity)),
         "Gebruik alleen numeriek waarden (geen tekst)."),
    need(length(data$concentration) == length(data$activity),
         "Aantal concentraties en activiteiten moet gelijk zijn.")
  )
  data
})
```

```{r fit_double}
fit1 <- eventReactive(input$fit_double, {
  req(data1())
  dir.MM(data1(), plot = FALSE)
})

fit2 <- eventReactive(input$fit_double, {
  req(data2())
  dir.MM(data2(), plot = FALSE)
})
```

```{r double_plot}
output$double_plot <- renderPlot({
  req(data1(), data2(), fit1(), fit2())
  
  ggplot() +
    geom_point(data = data1(),
               aes(x = concentration, y = activity, color = "Dataset 1"),
               shape = 4, size = 3) +
    geom_line(data = fit1()$data,
              aes(x = S, y = fitted_v, color = "Fit 1"),
              size = 1) +
    geom_point(data = data2(),
               aes(x = concentration, y = activity, color = "Dataset 2"),
               shape = 3, size = 3) +
    geom_line(data = fit2()$data,
              aes(x = S, y = fitted_v, color = "Fit 2"),
              size = 1) +
    
    scale_color_manual(values = c(
      "Dataset 1" = "deepskyblue4",
      "Fit 1" = "deepskyblue",
      "Dataset 2" = "deeppink4",
      "Fit 2" = "deeppink"
    )) +
    
    labs (
      title = "MM-curve gefit door gemeten datapunten",
      x = "Concentratie",
      y = "Activiteit",
      color = "Legenda"
    ) +
    
    theme_minimal() +
    theme(
      plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
      axis.title = element_text(face = "bold")
    )
})
```